Added function: Filter by winning percentage
micso/easy-steamgifts pull request #4
Opened 2017-01-05 09:18 UTC by dickstar

Thanks for your sharing.
I added a function: "Filter by winning percentage", help me to focus on the high winning probability giveaways.
It only add some necessary code like your style, and didn't conflict with your original programs at all.
I wish you will also like this function.

2017-01-17 20:31 UTC, bmxmiso requested changes
Just small requests

2017-01-17 20:31 UTC, bmxmiso commented on README.md
> +### Filter by winning Percent
stick to the general format and write "Percent" using lowercase

2017-01-17 20:31 UTC, bmxmiso commented on manifest.json
> +    "version": "2.5.2",
New features increment MINOR version so please use "2.6.0" number.

2017-01-17 20:37 UTC, micso commented
bmxmiso is my 2nd account (forgot to switch) ;)

2017-01-18 06:09 UTC, dickstar commented on README.md
> +### Filter by winning Percent
of course, thank u

2017-01-18 08:58 UTC, micso approved these changes

2017-01-24 10:12 UTC, merged

2017-01-24 10:35 UTC, micso commented
Published